// Auto-generated by scripts/sync-openai-types.mjs. Do not edit manually.
/// <reference path="./node_modules/openai/index.d.ts" />
export * from '../dist/index.d.cts'
export { default } from '../dist/index.d.cts'
