import { StorageProviderType, ModelProviderType } from '@prisma/client'
import { ModelProviderConfig } from '@/types'

export const modelProviderConfigs: ModelProviderConfig[] = [
  {
    slug: 'openai',
    type: ModelProviderType.OPENAI,
    name: 'OpenAI',
    description: 'Assistants API, Completions API, Function calling',
    iconUrl: '/images/openai-logo-square-light.svg',
    logoUrl: '/images/openai-logo-light.png',
    dashboardUrl: 'https://platform.openai.com/api-keys',
    modelSlugs: [
      'gpt-4o-mini',
      'gpt-4o-mini-2024-07-18',
      'gpt-4o',
      'gpt-4o-2024-11-20',
      'gpt-4o-2024-05-13',
      'chatgpt-4o-latest',
      'o1-preview',
      'o1-preview-2024-09-12',
      'o1-mini',
      'o1-mini-2024-09-12',
    ],
    storageProviderTypes: [
      StorageProviderType.SUPERINTERFACE_CLOUD,
      StorageProviderType.OPENAI,
      StorageProviderType.OPENAI_RESPONSES,
    ],
    isFunctionCallingAvailable: true,
  },
  {
    slug: 'azure-openai',
    type: ModelProviderType.AZURE_OPENAI,
    name: 'Azure OpenAI',
    description: 'Assistants API, Completions API, Function calling',
    iconUrl: '/images/microsoft-azure-logo-square.svg',
    logoUrl: '/images/microsoft-azure-logo-square.svg',
    dashboardUrl: 'https://ai.azure.com/playground/assistants',
    modelSlugs: [
      'gpt-4o-mini',
      'gpt-4o-mini-2024-07-18',
      'gpt-4o',
      'gpt-4o-2024-11-20',
      'gpt-4o-2024-05-13',
      'chatgpt-4o-latest',
      'o1-preview',
      'o1-preview-2024-09-12',
      'o1-mini',
      'o1-mini-2024-09-12',
    ],
    storageProviderTypes: [
      StorageProviderType.AZURE_OPENAI,
      StorageProviderType.SUPERINTERFACE_CLOUD,
      StorageProviderType.AZURE_RESPONSES,
    ],
    isFunctionCallingAvailable: true,
  },
  {
    slug: 'azure-ai-project',
    type: ModelProviderType.AZURE_AI_PROJECT,
    name: 'Azure AI Project',
    description: 'Azure AI Agents Runtime',
    iconUrl: '/images/microsoft-azure-logo-square.svg',
    logoUrl: '/images/microsoft-azure-logo-square.svg',
    dashboardUrl: 'https://ai.azure.com',
    modelSlugs: [
      'gpt-4o-mini',
      'gpt-4o-mini-2024-07-18',
      'gpt-4o',
      'gpt-4o-2024-11-20',
      'gpt-4o-2024-05-13',
      'chatgpt-4o-latest',
      'o1-preview',
      'o1-preview-2024-09-12',
      'o1-mini',
      'o1-mini-2024-09-12',
    ],
    storageProviderTypes: [StorageProviderType.AZURE_AGENTS],
    isFunctionCallingAvailable: true,
  },
  {
    slug: 'anthropic',
    type: ModelProviderType.ANTHROPIC,
    name: 'Anthropic',
    description: 'Completions API, Function calling',
    iconUrl: '/images/anthropic-logo-square.png',
    logoUrl: '/images/anthropic-logo-light.png',
    dashboardUrl: 'https://console.anthropic.com/settings/keys',
    modelSlugs: [
      'claude-3-5-sonnet-20241022',
      'claude-3-5-sonnet-20240620',
      'claude-3-opus-20240229',
      'claude-3-sonnet-20240229',
      'claude-3-5-haiku-20241022',
      'claude-3-haiku-20240307',
    ],
    storageProviderTypes: [StorageProviderType.SUPERINTERFACE_CLOUD],
    isFunctionCallingAvailable: true,
  },
  {
    slug: 'ollama',
    type: ModelProviderType.OLLAMA,
    name: 'Ollama',
    description: 'Completions API, Function calling',
    iconUrl: '/images/ollama-logo-square.jpg',
    logoUrl: '/images/ollama-logo-light.png',
    dashboardUrl: 'https://ollama.com',
    modelSlugs: [
      'qwq',
      'qwen2.5-coder:32b',
      'qwen2.5-coder:14b',
      'qwen2.5-coder:7b',
      'qwen2.5-coder:3b',
      'qwen2.5-coder:1.5b',
      'qwen2.5-coder:0.5b',
      'llama3.2',
      'llama3.2:1b',
    ],
    storageProviderTypes: [StorageProviderType.SUPERINTERFACE_CLOUD],
    isFunctionCallingAvailable: true,
  },
  {
    slug: 'google',
    type: ModelProviderType.GOOGLE,
    name: 'Google',
    description: 'Completions API, Function calling',
    iconUrl: '/images/google-gemini-logo-square.svg',
    logoUrl: '/images/google-gemini-logo-square.svg',
    dashboardUrl: 'https://aistudio.google.com/apikey',
    modelSlugs: ['gemini-2.0-flash-exp'],
    storageProviderTypes: [StorageProviderType.SUPERINTERFACE_CLOUD],
    isFunctionCallingAvailable: true,
  },
  {
    slug: 'mistral',
    type: ModelProviderType.MISTRAL,
    name: 'Mistral',
    description: 'Completions API, Function calling',
    iconUrl: '/images/mistral-logo-square.png',
    logoUrl: '/images/mistral-logo-light.svg',
    dashboardUrl: 'https://console.mistral.ai/api-keys/',
    modelSlugs: [
      'mistral-large-latest',
      'mistral-large-2407',
      'open-mistral-nemo',
      'open-mistral-nemo-2407',
      'open-mixtral-8x22b',
      'open-mixtral-8x7b',
      'open-mistral-7b',
    ],
    storageProviderTypes: [StorageProviderType.SUPERINTERFACE_CLOUD],
    isFunctionCallingAvailable: true,
  },
  {
    slug: 'groq',
    type: ModelProviderType.GROQ,
    name: 'Groq',
    description: 'Completions API, Function calling',
    iconUrl: '/images/groq-logo-square.png',
    logoUrl: '/images/groq-logo-light2.png',
    dashboardUrl: 'https://console.groq.com/keys',
    modelSlugs: [
      // 'llama-3.1-405b-reasoning',
      'meta-llama/llama-4-scout-17b-16e-instruct',
      'llama-3.1-8b-instant',
      'llama3-groq-70b-8192-tool-use-preview',
      'llama3-8b-8192',
      'llama3-70b-8192',
      'deepseek-r1-distill-llama-70b',
      // 'mixtral-8x7b-32768',
      'gemma-7b-it',
    ],
    storageProviderTypes: [StorageProviderType.SUPERINTERFACE_CLOUD],
    isFunctionCallingAvailable: true,
  },
  {
    slug: 'humiris',
    type: ModelProviderType.HUMIRIS,
    name: 'Humiris',
    description: 'Completions API',
    iconUrl: '/images/humiris-logo-square.png',
    logoUrl: '/images/humiris-logo-light2.png',
    dashboardUrl: 'https://platform.humiris.ai/api-key',
    modelSlugs: ['Humiris/humiris-moai'],
    storageProviderTypes: [StorageProviderType.SUPERINTERFACE_CLOUD],
    isFunctionCallingAvailable: false,
  },
  {
    slug: 'together',
    type: ModelProviderType.TOGETHER,
    name: 'Together.ai',
    description: 'Completions API, Function calling',
    iconUrl: '/images/together-logo-square.png',
    logoUrl: '/images/together-logo-light.png',
    dashboardUrl: 'https://api.together.xyz/settings/api-keys',
    modelSlugs: [
      'meta-llama/Llama-4-Scout-17B-16E-Instruct',
      'meta-llama/Llama-3-70b-chat-hf',
      'mistralai/Mixtral-8x7B-Instruct-v0.1',
      'togethercomputer/RedPajama-INCITE-Chat-3B-v1',
      'togethercomputer/CodeLlama-34b-Instruct',
    ],
    storageProviderTypes: [StorageProviderType.SUPERINTERFACE_CLOUD],
    isFunctionCallingAvailable: true,
  },
  {
    slug: 'perplexity',
    type: ModelProviderType.PERPLEXITY,
    name: 'Perplexity',
    description: 'Completions API, Function calling',
    iconUrl: '/images/perplexity-logo-square.png',
    logoUrl: '/images/perplexity-logo-light2.png',
    dashboardUrl: 'https://www.perplexity.ai/settings/api',
    modelSlugs: [
      'llama-3.1-sonar-small-128k-online',
      'llama-3.1-sonar-large-128k-online',
      'llama-3.1-sonar-huge-128k-online',
      'llama-3.1-sonar-small-128k-chat',
      'llama-3.1-sonar-large-128k-chat',
      'llama-3.1-8b-instruct',
      'llama-3.1-70b-instruct',
    ],
    storageProviderTypes: [StorageProviderType.SUPERINTERFACE_CLOUD],
    isFunctionCallingAvailable: true,
  },
  {
    slug: 'open-router',
    type: ModelProviderType.OPEN_ROUTER,
    name: 'Open Router',
    description: 'Completions API, Function calling',
    iconUrl: '/images/open-router-logo-square-light.svg',
    logoUrl: '/images/open-router-logo-light.svg',
    dashboardUrl: 'https://openrouter.ai/settings/keys',
    modelSlugs: [
      'openai/o1-mini',
      'openai/o1-preview',
      'openai/gpt-4o-mini',
      'qwen/qwen-2.5-72b-instruct',
    ],
    storageProviderTypes: [StorageProviderType.SUPERINTERFACE_CLOUD],
    isFunctionCallingAvailable: true,
  },
]
